 - name: "Deployin Java app on tomcat server"
   hosts: all
   become: true
   tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/upshiftnow/addressbook 
        dest: /home/ubuntu/finalproject
        clone: yes
        update: yes
       
    - name: "Install Maven using Ansible"
      apt:
          name: "maven"
          state: present
          update_cache: yes
          
    - name: Change the working directory
      ansible.builtin.shell:
        cmd: mvn compile                   
        chdir: /home/ubuntu/finalproject/src/main/java/com/vaadin/tutorial/addressbook
