 - hosts: all
   tasks:
   - name: Clone a github repository
     git:
       repo: https://github.com/vaadin/addressbook
       dest: /home/ubuntu/project
       clone: yes
       update: yes
       
  - name: Install Maven using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - maven
